### ISSUE TITLE
SQLMap

### ISSUE THREAD

**Issue by oldkingcone** [r0oth3x49/ghauri#36]
Dude, this is SQLMap.

**Comment by r0oth3x49** [comment]
OK dude anything else?

**Comment by oldkingcone** [comment]
why are you trying to pass off sqlmap as your own work?

**Comment by r0oth3x49** [comment]
I would like to ignore you and your dumb question

**Comment by oldkingcone** [comment]
ok, ignore me. but you are still copying SQLMap and trying to pass it off as your own.

**Comment by r0oth3x49** [comment]
Ok. This is my work users have the choice to use it or not I am not forcing them. 

Again I am saying this is my work and not sqlmap you have the choice, I would suggest you stick to sqlmap.

**Comment by SebSept** [comment]
I currently use sqlmap.
It worth mentioning what are the differences and why choosing ghauri ?

**Comment by r0oth3x49** [comment]
@SebSept there are already multiple articles / posts regarding ghauri where people are having success with ghauri but not sqlmap, i am not directly comparing ghauri with sqlmap people did. I created this project because in my daily project work i have had face a look of issues configuring and spoonfeeding SQLMap to do it my way though the SQLi can be seen as very simple and straightforward, But still SQLmap was failing badly even in detection that's where few friends suggested me to go and create things on your own, I was having tons of scripts created for exploitation and i use to use it for different cases each time modifying it according to needs, So i thought why not to combine all these techniques into one single module that could benefit the community too and it is benefiting that is why people are liking this project and giving stars though before ghauri there were tons of other projects too but still people likes this because it is doing the work for them.

Even the stamparam look at the code saying in his tweet regarding ghauri, "rewrite of internals".
So internals are main here.

one example would be.
save a vulnerable http request to file (SQLi behind authentication)
and provide it to ghauri and sqlmap both you will see the results yourself. (I am not talking about custom config just a direct input with `-r` switch).

ghauri does the things in browser style as well as custom own way
automatically switches to different exfiltration method, bypasses.

again i am not comparing here both because ghauri needs many things to be implemented while SQLMap is full of features.
SQLMap is full of features but ghauri does the work for you.

after developing this tool i rarely use SQLMap over ghauri except few cases which is being improved day by day.

you can give it a try yourself.
This is my honest opinion.

**Comment by SebSept** [comment]
ok, now I got the point, thanks!
(imo, theses words deserves to be on the readme file.)
