### ISSUE TITLE
cannot run ghauri on macbook pro m1

### ISSUE THREAD

**Issue by AzhariRamadhan** [r0oth3x49/ghauri#66]
**Describe the bug**
after git pull the repo, ghauri cannot run, and show errors 

**Screenshots**
<img width="762" alt="Jepretan Layar 2023-05-04 pukul 21 29 27" src="https://user-images.githubusercontent.com/32870854/236239847-22125c2a-df62-4ba6-97d1-bf7f65cd36a8.png">

**Desktop (please complete the following information):**

 - OS: [MacOS]
 - Ghauri version which is causing the error (should be latest) [ghauri==1.1.9]

**Comment by r0oth3x49** [comment]
You should be running it with python3 instead of python2 which is not supported. Install it with pip3 or python3 -m pip install.

Install a package called python-is-python3 I don't know the exact name but it's similar. May be python3-is-python. 

This is what changes the default Python to 3 instead of 2
