### ISSUE TITLE
can't exploit/retrieve info

### ISSUE THREAD

**Issue by marcelo321** [r0oth3x49/ghauri#71]
Hi,

I am testing with ghauri and it fails to get any information after confirming there is a sql injection.

flags like `--hostname -b -c-curent-db --current-user --dbs` all of them fail with the same message:

```
[06:40:00] [INFO] retrieving the length of query output
[06:40:01] [INFO] retrieved: : 
[06:40:01] [WARNING] it was not possible to extract query output length for the SQL query provided.
```

I have seen this before in portswigger labs that are sqli vulnerable, so it is just failing to exploit most sqli and just detects them?

**Comment by r0oth3x49** [comment]
Portswigger which one

**Comment by r0oth3x49** [comment]
Will check with portswigger lab

**Comment by r0oth3x49** [comment]
@marcelo321 which portswigger lab can you share the link of the lab so that I can test on that specific one I have tested on multiple and works find for me so instead of wasting time on testing would be great if you share the link to lab where you are facing that issue otherwise I will have to close this as invalid
