### ISSUE TITLE
Couldnot exploit some special condition

### ISSUE THREAD

**Issue by patali09** [r0oth3x49/ghauri#77]
Ghauri couldnot exploit the special case like in this lab https://portswigger.net/web-security/sql-injection/blind/lab-sql-injection-visible-error-based .

![image](https://github.com/r0oth3x49/ghauri/assets/55197156/d92d6083-cd39-403f-8709-676fcb24745d)

**Comment by r0oth3x49** [comment]
Will take a look at this.

**Comment by r0oth3x49** [comment]
did you ever found such scenario in normal because this special case seems to be specific to this lab only and i have tested it manually, what i can do is to only add an identification of error for now not going to add payload for this specific case if ever in future you find such case in real targets instead of lab then re-open this issue and i will try adding payloads for such cases.

after testing the lab it seems there is limit of characters in query so you can only perform few things and is specific to lab that's why i am not going to add any solution to this.
