### ISSUE TITLE
Can't get to install it.

### ISSUE THREAD

**Issue by dongido001** [r0oth3x49/ghauri#9]
I have tried installing it following the instructions but I don't seem to get it to work:

```bash
➜  ghauri git:(main) python3 -m pip install -e .
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Obtaining file:///Users/*/projects/ghauri
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tldextract in /opt/homebrew/lib/python3.9/site-packages/tldextract-3.4.0-py3.9.egg (from ghauri==1.0.1-dev) (3.4.0)
Requirement already satisfied: colorama in /opt/homebrew/lib/python3.9/site-packages/colorama-0.4.5-py3.9.egg (from ghauri==1.0.1-dev) (0.4.5)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.9/site-packages/requests-2.28.1-py3.9.egg (from ghauri==1.0.1-dev) (2.28.1)
Requirement already satisfied: chardet in /opt/homebrew/lib/python3.9/site-packages/chardet-5.0.0-py3.9.egg (from ghauri==1.0.1-dev) (5.0.0)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/homebrew/lib/python3.9/site-packages/charset_normalizer-2.1.1-py3.9.egg (from requests->ghauri==1.0.1-dev) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages/idna-3.4-py3.9.egg (from requests->ghauri==1.0.1-dev) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages/urllib3-1.26.12-py3.9.egg (from requests->ghauri==1.0.1-dev) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages/certifi-2022.9.24-py3.9.egg (from requests->ghauri==1.0.1-dev) (2022.9.24)
Requirement already satisfied: requests-file>=1.4 in /opt/homebrew/lib/python3.9/site-packages/requests_file-1.5.1-py3.9.egg (from tldextract->ghauri==1.0.1-dev) (1.5.1)
Requirement already satisfied: filelock>=3.0.8 in /Users/*/Library/Python/3.9/lib/python/site-packages (from tldextract->ghauri==1.0.1-dev) (3.7.1)
Requirement already satisfied: six in /Users/*/Library/Python/3.9/lib/python/site-packages (from requests-file>=1.4->tldextract->ghauri==1.0.1-dev) (1.16.0)
Installing collected packages: ghauri
  Attempting uninstall: ghauri
    Found existing installation: ghauri 1.0.1.dev0
    Uninstalling ghauri-1.0.1.dev0:
      Successfully uninstalled ghauri-1.0.1.dev0
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Running setup.py develop for ghauri
Successfully installed ghauri
WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
➜  ghauri git:(main) ghauri
➜  ghauri git:(main) ghauri --help
zsh: command not found: ghauri
➜  ghauri git:(main) ghauri       
zsh: command not found: ghauri
```

**Comment by r0oth3x49** [comment]
Tested on Ubuntu and win works fine don't have Mac will see if I can arrange one. Its installed but not accessible for some reason

**Comment by muneef1994** [comment]
──(kali㉿kali)-[~/ghauri]
└─$ pip install --upgrade -r requirements.txt                                         
Defaulting to user installation because normal site-packages is not writeable
Collecting tldextract
  Downloading tldextract-3.4.0-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 790.9 kB/s eta 0:00:00
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.4.4)
Collecting colorama
  Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.25.1)
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (4.0.0)
Collecting chardet
  Downloading chardet-5.0.0-py3-none-any.whl (193 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: requests-file>=1.4 in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 1)) (3.2)
Collecting filelock>=3.0.8
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (1.26.5)
Installing collected packages: requests, filelock, colorama, chardet, tldextract
  WARNING: The script chardetect is installed in '/home/kali/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                           
  WARNING: The script tldextract is installed in '/home/kali/.local/bin' which is not on PATH.                                                
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                           
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.                                                                                                              
crackmapexec 5.2.2 requires bs4<0.0.2,>=0.0.1, which is not installed.                                                                        
crackmapexec 5.2.2 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 1.7.0.dev0 which is incompatible.                                         
crackmapexec 5.2.2 requires pylnk3<0.4.0,>=0.3.0, but you have pylnk3 0.4.2 which is incompatible.                                            
Successfully installed chardet-5.0.0 colorama-0.4.5 filelock-3.8.0 requests-2.28.1 tldextract-3.4.0                                           
                                                                                                                                              
┌──(kali㉿kali)-[~/ghauri]
└─$ python setup.py install
/usr/lib/python3/dist-packages/setuptools/dist.py:507: UserWarning: The version specified ('1.0.1#dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/test-easy-install-307888.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.9/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

──(kali㉿kali)-[~/ghauri]
└─$ pip install --upgrade -r requirements.txt                                         
Defaulting to user installation because normal site-packages is not writeable
Collecting tldextract
  Downloading tldextract-3.4.0-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 790.9 kB/s eta 0:00:00
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (0.4.4)
Collecting colorama
  Downloading colorama-0.4.5-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.25.1)
Collecting requests
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 1.8 MB/s eta 0:00:00
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (4.0.0)
Collecting chardet
  Downloading chardet-5.0.0-py3-none-any.whl (193 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: requests-file>=1.4 in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from tldextract->-r requirements.txt (line 1)) (3.2)
Collecting filelock>=3.0.8
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 3)) (1.26.5)
Installing collected packages: requests, filelock, colorama, chardet, tldextract
  WARNING: The script chardetect is installed in '/home/kali/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                           
  WARNING: The script tldextract is installed in '/home/kali/.local/bin' which is not on PATH.                                                
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                           
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.                                                                                                              
crackmapexec 5.2.2 requires bs4<0.0.2,>=0.0.1, which is not installed.                                                                        
crackmapexec 5.2.2 requires neo4j<5.0.0,>=4.1.1, but you have neo4j 1.7.0.dev0 which is incompatible.                                         
crackmapexec 5.2.2 requires pylnk3<0.4.0,>=0.3.0, but you have pylnk3 0.4.2 which is incompatible.                                            
Successfully installed chardet-5.0.0 colorama-0.4.5 filelock-3.8.0 requests-2.28.1 tldextract-3.4.0                                           
                                                                                                                                              
┌──(kali㉿kali)-[~/ghauri]
└─$ python setup.py install
/usr/lib/python3/dist-packages/setuptools/dist.py:507: UserWarning: The version specified ('1.0.1#dev') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  warnings.warn(
running install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.9/dist-packages/test-easy-install-307888.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.9/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.




its not working for kali..

**Comment by r0oth3x49** [comment]
if you are running the installation with root you should be using sudo.

**Comment by r0oth3x49** [comment]
@muneef1994  you should be adding ` '/home/kali/.local/bin'` to path because the error clearly says it all.
```
WARNING: The script chardetect is installed in '/home/kali/.local/bin' which is not on PATH.
```

**Comment by r0oth3x49** [comment]
try installing again by following the latest README file hope this will fix the issue.
