### ISSUE TITLE
Can you add some queries

### ISSUE THREAD

**Issue by justtrader2023** [r0oth3x49/ghauri#97]
ghuair is the best but need some

1 - common tables and columns for hard servers 
2 - sql shell need more modification it get nothing from any query 
3 - shell upload :) will be help
4- -- password to get root password

**Comment by r0oth3x49** [comment]
Sql-shell is a little bit advance as it requires you to prepare the complete query instead of normal query like select * from abc
You should be using limit etc within your query. You can say a sql-shell is tool to handle your manual queries just like you do within the burp 

For shell upload and --password feature will take a look but not in near future.
